subClassOf('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#Bus','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hardware').
subClassOf('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#CUDA','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#software').
subClassOf('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#Cache','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#Memory').
subClassOf('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#ConstantMemory','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#Memory').
subClassOf('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#Core','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hardware').
subClassOf('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#Die','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hardware').
subClassOf('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#Die',someValuesFrom('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#consistsOf','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#TPC')).
subClassOf('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#GPU','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hardware').
subClassOf('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#GPU',someValuesFrom('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#consistsOf','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#Memory')).
subClassOf('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#GPU',someValuesFrom('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#consistsOf','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#Processor')).
subClassOf('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#GlobalMemory','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#Memory').
subClassOf('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#L1','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#Cache').
subClassOf('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#L1_constant','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#L1').
subClassOf('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#L1_global','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#L1').
subClassOf('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#L1_readonly','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#L1').
subClassOf('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#L1_texture','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#L1').
subClassOf('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#L2','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#Cache').
subClassOf('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#L2_constant','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#L2').
subClassOf('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#L2_global','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#L2').
subClassOf('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#L2_readonly','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#L2').
subClassOf('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#L2_texture','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#L2').
subClassOf('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#Memory','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hardware').
subClassOf('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#MemoryBus','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#Bus').
subClassOf('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#MemoryBus',someValuesFrom('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#busWidth','http://www.w3.org/2001/XMLSchema#integer')).
subClassOf('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#Processor','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hardware').
subClassOf('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#Processor',someValuesFrom('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#TPCPerDie','http://www.w3.org/2001/XMLSchema#integer')).
subClassOf('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#Processor',someValuesFrom('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#CoresPerSM','http://www.w3.org/2001/XMLSchema#integer')).
subClassOf('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#Processor',someValuesFrom('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#SMPerTPC','http://www.w3.org/2001/XMLSchema#integer')).
subClassOf('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#Processor',someValuesFrom('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#membus','http://www.w3.org/2001/XMLSchema#integer')).
subClassOf('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#ReadOnlyMemory','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#Memory').
subClassOf('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#SM','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hardware').
subClassOf('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#SM',someValuesFrom('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#consistsOf','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#Core')).
subClassOf('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#SharedMemory','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#Memory').
subClassOf('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#TPC','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hardware').
subClassOf('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#TPC',someValuesFrom('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#consistsOf','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#SM')).
subClassOf('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#Tesla','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#GPU').
subClassOf('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#TextureMemory','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#Memory').
subClassOf('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#blockDim','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#built-inVariable').
subClassOf('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#blockIdx','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#built-inVariable').
subClassOf('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#built-inVariable','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#CUDA').
subClassOf('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#grid','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#CUDA').
subClassOf('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#grid',someValuesFrom('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#blocksPerGrid','http://www.w3.org/2001/XMLSchema#integer')).
subClassOf('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#grid',someValuesFrom('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#organizedInto','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#threadBlock')).
subClassOf('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hardwareScope','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#scope').
subClassOf('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hardwareScope',oneOf(['http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#core','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#die','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#tpc','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#sm'])).
subClassOf('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#softwareScope','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#scope').
subClassOf('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#softwareScope',oneOf(['http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#block','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#warp','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#grid'])).
subClassOf('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#thread','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#CUDA').
subClassOf('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#thread','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#software').
subClassOf('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#threadBlock','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#CUDA').
subClassOf('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#threadBlock',someValuesFrom('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasDimension',intersectionOf([datatypeRestriction('http://www.w3.org/2001/XMLSchema#integer',[facetRestriction(minInclusive,literal(type('http://www.w3.org/2001/XMLSchema#integer','1')))]),datatypeRestriction('http://www.w3.org/2001/XMLSchema#integer',[facetRestriction(maxInclusive,literal(type('http://www.w3.org/2001/XMLSchema#integer','3')))])]))).
subClassOf('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#threadBlock',someValuesFrom('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#threadsPerBlock',datatypeRestriction('http://www.w3.org/2001/XMLSchema#integer',[facetRestriction(maxInclusive,literal(type('http://www.w3.org/2001/XMLSchema#integer','1024')))]))).
subClassOf('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#threadID','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#CUDA').
subClassOf('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#threadIdx','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#built-inVariable').
subClassOf('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#warp','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#CUDA').
transitiveProperty('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#consistsOf').
transitiveProperty('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasUpperLevel').
subPropertyOf('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasLowerLevel','http://www.w3.org/2002/07/owl#topObjectProperty').
subPropertyOf('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#CoresPerSM','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasNumberValue').
subPropertyOf('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#SMPerTPC','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasNumberValue').
subPropertyOf('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#TPCPerDie','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasNumberValue').
subPropertyOf('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#banks','http://www.w3.org/2002/07/owl#topDataProperty').
subPropertyOf('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#blocksPerGrid','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasNumberValue').
subPropertyOf('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasBlockSizeValue','http://www.w3.org/2002/07/owl#topDataProperty').
subPropertyOf('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#nubmerOfCoresValue','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasNumberValue').
subPropertyOf('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#numberOfDiesValue','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasNumberValue').
subPropertyOf('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#numberOfThreadsValue','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasNumberValue').
subPropertyOf('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#softwareManageable','http://www.w3.org/2002/07/owl#topDataProperty').
subPropertyOf('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#threadsPerBlock','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasNumberValue').
functionalProperty('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasDimension').
functionalProperty('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#nubmerOfCoresValue').
functionalProperty('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#softwareManageable').
propertyRange('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#scope',unionOf(['http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#grid','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#threadBlock','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#warp'])).
propertyRange('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#shareScope',unionOf(['http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#Core','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#Die','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#SM','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#TPC'])).
propertyRange('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#CoresPerSM','http://www.w3.org/2001/XMLSchema#integer').
propertyRange('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#SMPerTPC','http://www.w3.org/2001/XMLSchema#integer').
propertyRange('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#TPCPerDie','http://www.w3.org/2001/XMLSchema#integer').
propertyRange('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#blocksPerGrid','http://www.w3.org/2001/XMLSchema#integer').
propertyRange('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasDimension','http://www.w3.org/2001/XMLSchema#integer').
propertyRange('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasID','http://www.w3.org/2001/XMLSchema#integer').
propertyRange('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasName','http://www.w3.org/2001/XMLSchema#string').
propertyRange('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#nubmerOfCoresValue','http://www.w3.org/2001/XMLSchema#integer').
propertyRange('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#numberOfDiesValue','http://www.w3.org/2001/XMLSchema#integer').
propertyRange('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#numberOfThreadsValue','http://www.w3.org/2001/XMLSchema#integer').
propertyRange('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#softwareManageable','http://www.w3.org/2001/XMLSchema#boolean').
propertyRange('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#threadsPerBlock','http://www.w3.org/2001/XMLSchema#integer').
inverseProperties('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasLowerLevel','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasUpperLevel').
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#comment','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#membus',literal(type('http://www.w3.org/2001/XMLSchema#integer',bytes))).
annotationAssertion('http://www.w3.org/2000/01/rdf-schema#comment','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#pieces',literal(?)).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#pieces','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#L1',literal(type('http://www.w3.org/2001/XMLSchema#integer','1'))).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#threadsGroup','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#L1',literal(type('http://www.w3.org/2001/XMLSchema#integer','32'))).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasID','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#L1',literal(type('http://www.w3.org/2001/XMLSchema#integer','9'))).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#softwareManageable','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#L1',literal(type('http://www.w3.org/2001/XMLSchema#boolean',false))).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasSizeValue','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#L1',literal('16 K')).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasBlockSizeValue','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#L1',literal('128 B')).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasLatencyValue','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#L1',literal('80 clk')).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#accessible','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#L1',literal(rw)).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#shareScope','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#L1','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#sm').
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#pieces','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#L2',literal(type('http://www.w3.org/2001/XMLSchema#integer','2'))).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#threadsGroup','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#L2',literal(type('http://www.w3.org/2001/XMLSchema#integer','32'))).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasLatencyValue','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#L2',literal(type('http://www.w3.org/2001/XMLSchema#integer','390'))).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#threadsGroup','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#L2',literal(type('http://www.w3.org/2001/XMLSchema#integer','4'))).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasID','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#L2',literal(type('http://www.w3.org/2001/XMLSchema#integer','7'))).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#softwareManageable','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#L2',literal(type('http://www.w3.org/2001/XMLSchema#boolean',false))).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#accessible','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#L2',literal(rw)).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasBlockSizeValue','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#L2',literal('32 B')).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasSizeValue','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#L2',literal('768 K')).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasUpperLevel','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#L2','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#L1').
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasLowerLevel','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#L2','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075TextureMemory_A').
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasLowerLevel','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#L2','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075TextureMemory_B').
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasLowerLevel','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#L2','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075TextureMemory_C').
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#shareScope','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#L2','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#die').
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#TPCPerDie','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075',literal(type('http://www.w3.org/2001/XMLSchema#integer','16'))).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#consistsOf','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075ConstantMemory').
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#consistsOf','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075GlobalMemory').
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#consistsOf','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075Processor').
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#consistsOf','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075ReadOnlyMemory').
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#consistsOf','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075SharedMemory').
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#consistsOf','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075TextureMemory_A').
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasID','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075ConstantMemory',literal(type('http://www.w3.org/2001/XMLSchema#integer','1'))).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#pieces','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075ConstantMemory',literal(type('http://www.w3.org/2001/XMLSchema#integer','1'))).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#threadsGroup','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075ConstantMemory',literal(type('http://www.w3.org/2001/XMLSchema#integer','32'))).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#softwareManageable','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075ConstantMemory',literal(type('http://www.w3.org/2001/XMLSchema#boolean',true))).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#accessible','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075ConstantMemory',literal(r)).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasSizeValue','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075ConstantMemory',literal('64 K')).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasLatencyValue','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075ConstantMemory',literal('360 clk')).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasUpperLevel','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075ConstantMemory','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#cL2').
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#shareScope','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075ConstantMemory','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#die').
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#pieces','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075GlobalMemory',literal(type('http://www.w3.org/2001/XMLSchema#integer','1'))).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#threadsGroup','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075GlobalMemory',literal(type('http://www.w3.org/2001/XMLSchema#integer','32'))).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasID','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075GlobalMemory',literal(type('http://www.w3.org/2001/XMLSchema#integer','8'))).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#softwareManageable','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075GlobalMemory',literal(type('http://www.w3.org/2001/XMLSchema#boolean',true))).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#accessible','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075GlobalMemory',literal(rw)).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#concurrencyFactor','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075GlobalMemory',literal('<0.1 0.5>')).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasLatencyValue','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075GlobalMemory',literal('600 clk')).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasBlockSizeValue','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075GlobalMemory',literal('128 B')).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasSizeValue','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075GlobalMemory',literal('5375 M')).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasUpperLevel','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075GlobalMemory','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#L2').
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#shareScope','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075GlobalMemory','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#die').
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#numberOfDiesValue','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075Processor',literal(type('http://www.w3.org/2001/XMLSchema#integer','1'))).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#SMPerTPC','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075Processor',literal(type('http://www.w3.org/2001/XMLSchema#integer','1'))).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#TPCPerDie','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075Processor',literal(type('http://www.w3.org/2001/XMLSchema#integer','16'))).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#CoresPerSM','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075Processor',literal(type('http://www.w3.org/2001/XMLSchema#integer','32'))).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#membus','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075Processor',literal(type('http://www.w3.org/2001/XMLSchema#integer','48'))).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#pieces','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075SharedMemory',literal(type('http://www.w3.org/2001/XMLSchema#integer','1'))).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#threadsGroup','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075SharedMemory',literal(type('http://www.w3.org/2001/XMLSchema#integer','32'))).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#banks','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075SharedMemory',literal(type('http://www.w3.org/2001/XMLSchema#integer','32'))).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasID','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075SharedMemory',literal(type('http://www.w3.org/2001/XMLSchema#integer','4'))).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#softwareManageable','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075SharedMemory',literal(type('http://www.w3.org/2001/XMLSchema#boolean',true))).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasLatencyValue','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075SharedMemory',literal('48 clk')).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#accessible','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075SharedMemory',literal(rw)).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasSizeValue','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075SharedMemory',literal('48 K')).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#shareScope','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075SharedMemory','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#sm').
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#pieces','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075TextureMemory_A',literal(type('http://www.w3.org/2001/XMLSchema#integer','1'))).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#threadsGroup','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075TextureMemory_A',literal(type('http://www.w3.org/2001/XMLSchema#integer','4'))).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasID','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075TextureMemory_A',literal(type('http://www.w3.org/2001/XMLSchema#integer','5'))).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#softwareManageable','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075TextureMemory_A',literal(type('http://www.w3.org/2001/XMLSchema#boolean',true))).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#concurrencyFactor','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075TextureMemory_A',literal('<0.1 0.5>')).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#accessible','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075TextureMemory_A',literal(r)).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasLatencyValue','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075TextureMemory_A',literal('617 clk')).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasSizeValue','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075TextureMemory_A',literal('5375 M')).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#shareScope','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075TextureMemory_A','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#die').
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasDimension','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075TextureMemory_B',literal(type('http://www.w3.org/2001/XMLSchema#integer','1'))).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasID','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075TextureMemory_B',literal(type('http://www.w3.org/2001/XMLSchema#integer','5'))).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasSizeValue','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075TextureMemory_B',literal('128 ME')).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasBlockSizeValue','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075TextureMemory_B',literal('32 B')).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasDimension','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075TextureMemory_C',literal(type('http://www.w3.org/2001/XMLSchema#integer','2'))).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasSizeValue','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075TextureMemory_C',literal('<64 KE 64 KE>')).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasBlockSizeValue','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075TextureMemory_C',literal('<16 B 2>')).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#pieces','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#cL1',literal(type('http://www.w3.org/2001/XMLSchema#integer','1'))).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasID','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#cL1',literal(type('http://www.w3.org/2001/XMLSchema#integer','3'))).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#threadsGroup','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#cL1',literal(type('http://www.w3.org/2001/XMLSchema#integer','32'))).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#softwareManageable','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#cL1',literal(type('http://www.w3.org/2001/XMLSchema#boolean',false))).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasSizeValue','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#cL1',literal('4 K')).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasBlockSizeValue','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#cL1',literal('64 B')).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasLatencyValue','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#cL1',literal('48 clk')).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#shareScope','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#cL1','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#sm').
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#pieces','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#cL2',literal(type('http://www.w3.org/2001/XMLSchema#integer','1'))).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasID','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#cL2',literal(type('http://www.w3.org/2001/XMLSchema#integer','2'))).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#softwareManageable','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#cL2',literal(type('http://www.w3.org/2001/XMLSchema#boolean',false))).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasLatencyValue','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#cL2',literal('140 clk')).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#accessible','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#cL2',literal(r)).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasSizeValue','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#cL2',literal('32 K')).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasBlockSizeValue','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#cL2',literal('256 B')).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasUpperLevel','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#cL2','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#cL1').
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#shareScope','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#cL2','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#die').
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasSizeValue','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#tL1',literal(type('http://www.w3.org/2001/XMLSchema#integer','12'))).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasLatencyValue','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#tL1',literal(type('http://www.w3.org/2001/XMLSchema#integer','208'))).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasID','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#tL1',literal(type('http://www.w3.org/2001/XMLSchema#integer','6'))).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#softwareManageable','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#tL1',literal(type('http://www.w3.org/2001/XMLSchema#boolean',false))).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#accessible','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#tL1',literal(r)).
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasLowerLevel','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#tL1','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#L2').
propertyAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#shareScope','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#tL1','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#sm').
classAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#Cache','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#L1').
classAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#Cache','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#L2').
classAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#Tesla','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075').
classAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#ConstantMemory','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075ConstantMemory').
classAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#GlobalMemory','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075GlobalMemory').
classAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#Processor','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075Processor').
classAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#ReadOnlyMemory','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075ReadOnlyMemory').
classAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#SharedMemory','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075SharedMemory').
classAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#TextureMemory','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075TextureMemory_A').
classAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#TextureMemory','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075TextureMemory_B').
classAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#TextureMemory','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075TextureMemory_C').
classAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#scope','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#block').
classAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#L1_constant','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#cL1').
classAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#L2_constant','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#cL2').
classAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#scope','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#core').
classAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#scope','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#die').
classAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#scope','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#grid').
classAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#scope','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#sm').
classAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#L1_texture','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#tL1').
classAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#scope','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#tpc').
classAssertion('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#scope','http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#warp').
namedIndividual('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#L1').
namedIndividual('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#L2').
namedIndividual('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075').
namedIndividual('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075ConstantMemory').
namedIndividual('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075GlobalMemory').
namedIndividual('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075Processor').
namedIndividual('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075ReadOnlyMemory').
namedIndividual('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075SharedMemory').
namedIndividual('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075TextureMemory_A').
namedIndividual('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075TextureMemory_B').
namedIndividual('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#M2075TextureMemory_C').
namedIndividual('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#block').
namedIndividual('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#cL1').
namedIndividual('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#cL2').
namedIndividual('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#core').
namedIndividual('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#die').
namedIndividual('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#grid').
namedIndividual('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#sm').
namedIndividual('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#tL1').
namedIndividual('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#tpc').
namedIndividual('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#warp').
objectProperty('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#consistsOf').
objectProperty('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasBlockSize').
objectProperty('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasLatency').
objectProperty('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasLowerLevel').
objectProperty('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasNumber').
objectProperty('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasSize').
objectProperty('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasUpperLevel').
objectProperty('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#organizedInto').
objectProperty('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#scope').
objectProperty('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#shareScope').
dataProperty('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#CoresPerSM').
dataProperty('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#SMPerTPC').
dataProperty('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#TPCPerDie').
dataProperty('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#accessible').
dataProperty('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#banks').
dataProperty('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#blocksPerGrid').
dataProperty('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#busWidth').
dataProperty('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#concurrencyFactor').
dataProperty('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasBlockSizeValue').
dataProperty('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasDimension').
dataProperty('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasID').
dataProperty('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasLatencyValue').
dataProperty('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasName').
dataProperty('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasNumberValue').
dataProperty('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasSizeValue').
dataProperty('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hasValue').
dataProperty('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#membus').
dataProperty('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#nubmerOfCoresValue').
dataProperty('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#numberOfDiesValue').
dataProperty('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#numberOfThreadsValue').
dataProperty('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#pieces').
dataProperty('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#softwareManageable').
dataProperty('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#threadsGroup').
dataProperty('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#threadsPerBlock').
annotationProperty('http://www.w3.org/2000/01/rdf-schema#label').
annotationProperty('http://www.w3.org/2000/01/rdf-schema#comment').
class('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#Bus').
class('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#CUDA').
class('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#Cache').
class('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#ConstantMemory').
class('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#Core').
class('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#Die').
class('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#GPU').
class('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#GlobalMemory').
class('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#L1').
class('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#L1_constant').
class('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#L1_global').
class('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#L1_readonly').
class('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#L1_texture').
class('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#L2').
class('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#L2_constant').
class('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#L2_global').
class('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#L2_readonly').
class('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#L2_texture').
class('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#Memory').
class('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#MemoryBus').
class('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#Processor').
class('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#ReadOnlyMemory').
class('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#SM').
class('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#SharedMemory').
class('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#TPC').
class('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#Tesla').
class('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#TextureMemory').
class('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#blockDim').
class('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#blockIdx').
class('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#built-inVariable').
class('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#grid').
class('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hardware').
class('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#hardwareScope').
class('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#scope').
class('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#software').
class('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#softwareScope').
class('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#thread').
class('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#threadBlock').
class('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#threadID').
class('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#threadIdx').
class('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL#warp').
ontology('http://www.semanticweb.org/yzhao30/ontologies/2015/3/MSL').
